remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: League of Legends Win/Loss Prediction Model
description: This is a website that reports my finding on model building for my DSC80 Project